import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Providers } from "./providers";
import React from "react";
import { UserMenu } from "../components/UserMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-neutral-50 text-neutral-900 dark:bg-neutral-950 dark:text-neutral-50`}>        
        <Providers>
          <div className="flex h-screen w-screen overflow-hidden">
            {/* Sidebar */}
            <aside className="w-56 shrink-0 border-r bg-white/70 dark:bg-neutral-900/70 backdrop-blur-sm border-neutral-200 dark:border-neutral-800 flex flex-col">
              <div className="h-14 flex items-center px-4 border-b border-neutral-200 dark:border-neutral-800 font-semibold tracking-tight text-sm">
                User Console
              </div>
              <nav className="flex-1 overflow-y-auto py-4">
                <ul className="space-y-1 px-3 text-sm">
                  <li>
                    <Link href="/apps" className="block rounded px-3 py-2 hover:bg-neutral-100 dark:hover:bg-neutral-800 transition">Apps</Link>
                  </li>
                  <li>
                    <Link href="/me" className="block rounded px-3 py-2 hover:bg-neutral-100 dark:hover:bg-neutral-800 transition">My Profile</Link>
                  </li>
                </ul>
              </nav>
              <div className="p-3 text-[10px] text-neutral-400">v1.0.0</div>
            </aside>
            {/* Main content area */}
            <div className="flex flex-col flex-1 min-w-0">
              {/* Top bar */}
              <header className="h-14 border-b border-neutral-200 dark:border-neutral-800 flex items-center justify-between px-4 bg-white/60 dark:bg-neutral-900/60 backdrop-blur-sm">
                <div className="font-medium text-sm">Dashboard</div>
                <div className="flex items-center gap-3">
                  <UserMenu />
                </div>
              </header>
              <main className="flex-1 overflow-y-auto p-6">
                {children}
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
